server {
    listen 80;
    server_name front.rucode.cn;

    location /.well-known/acme-challenge/ {
        root /www/wwwroot/front.rucode.cn;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name front.rucode.cn;

    root /www/wwwroot/front.rucode.cn;
    index index.html;
    client_max_body_size 20m;

    ssl_certificate /www/server/panel/vhost/cert/front.rucode.cn/fullchain.pem;
    ssl_certificate_key /www/server/panel/vhost/cert/front.rucode.cn/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL_FRONT:10m;
    ssl_session_timeout 10m;

    gzip on;
    gzip_min_length 1024;
    gzip_comp_level 5;
    gzip_types text/plain text/css application/javascript application/json application/xml image/svg+xml font/woff2;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|woff2?|png|jpg|jpeg|gif|svg|ico|webp)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
        try_files $uri =404;
    }
}
